# Generated by Django 2.2 on 2023-08-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=True, max_length=255)),
                ('title', models.CharField(default=True, max_length=255)),
                ('image', models.URLField(default=True)),
                ('link', models.URLField(default=True)),
                ('price', models.CharField(default=True, max_length=50)),
                ('description', models.TextField(default=True)),
                ('model', models.CharField(default=True, max_length=255)),
                ('ram', models.CharField(default=True, max_length=50)),
                ('generation', models.CharField(default=True, max_length=50)),
                ('display', models.CharField(default=True, max_length=50)),
                ('storage', models.CharField(default=True, max_length=50)),
            ],
        ),
    ]
