# Generated by Django 2.2 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='graphics',
            field=models.CharField(blank=True, default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_display_resulation',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ports_and_connectivity',
            field=models.CharField(blank=True, default=True, max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='touchscreen',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warrenty',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
