# Generated by Django 2.2 on 2023-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processor_speed',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
    ]
