# Generated by Django 2.2 on 2023-08-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_processor_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='processor_speed',
            new_name='p_speed',
        ),
    ]
