# Generated by Django 2.2 on 2023-08-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230818_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_speed',
        ),
    ]
