# Generated by Django 2.2 on 2023-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_p_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_speed',
            field=models.CharField(blank=True, default=True, max_length=200),
        ),
    ]
