# Generated by Django 2.2 on 2023-08-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_p_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='generation',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='graphics',
            field=models.CharField(blank=True, default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='insurance',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_display_resulation',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_speed',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='ports_and_connectivity',
            field=models.CharField(blank=True, default='-', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='touchscreen',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrenty',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
