# Generated by Django 2.2 on 2023-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230819_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='logo_url',
            field=models.URLField(default=True),
        ),
    ]
