# Generated by Django 2.2 on 2023-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230821_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.URLField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.URLField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.URLField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo_url',
            field=models.URLField(blank=True, default=True),
        ),
    ]
