# Generated by Django 2.2 on 2023-08-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230821_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='logo_url',
        ),
    ]
