# Generated by Django 2.2 on 2023-08-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20230821_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=255)),
                ('brand', models.CharField(blank=True, default='-', max_length=100)),
                ('model', models.CharField(default=True, max_length=255)),
                ('image', models.URLField(default=True)),
                ('link', models.URLField(default=True)),
                ('price', models.CharField(default=True, max_length=50)),
                ('processor', models.CharField(blank=True, max_length=250)),
                ('processor_type', models.CharField(blank=True, max_length=100)),
                ('generation', models.CharField(default='-', max_length=50)),
                ('ram', models.CharField(default=True, max_length=50)),
                ('ram_type', models.CharField(blank=True, max_length=100)),
                ('ram_speed', models.CharField(blank=True, max_length=100)),
                ('graphics', models.CharField(blank=True, max_length=250)),
                ('graphics_type', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(default='-', max_length=50)),
                ('storage_type', models.CharField(blank=True, max_length=100)),
                ('display_size', models.CharField(blank=True, max_length=50)),
                ('touchscreen', models.CharField(blank=True, default='-', max_length=100)),
                ('maximum_display_resulation', models.CharField(blank=True, default='-', max_length=100)),
                ('battery', models.CharField(blank=True, default='-', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='-', max_length=200)),
                ('description', models.TextField(default='-')),
                ('color', models.CharField(blank=True, default='-', max_length=100)),
                ('warrenty', models.CharField(blank=True, default='-', max_length=100)),
                ('insurance', models.CharField(blank=True, default='-', max_length=100)),
            ],
        ),
    ]
