# Generated by Django 2.2 on 2023-08-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_filtered'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='display',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
