# Generated by Django 2.2 on 2023-08-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_filtered_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtered',
            name='display',
        ),
    ]
