# Generated by Django 2.2 on 2023-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_filtered_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='ramm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
