# Generated by Django 2.2 on 2023-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_filtered_ramm'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='processor_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
