# Generated by Django 2.2 on 2023-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_filtered_processor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='graphics_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
