# Generated by Django 2.2 on 2023-08-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_filtered_graphics_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtered',
            name='graphics_info',
        ),
    ]
