# Generated by Django 2.2 on 2023-08-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_filtered_graphics_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='ports_and_connectivity',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='filtered',
            name='pprice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='filtered',
            name='sstorage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
