# Generated by Django 2.2 on 2023-08-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20230827_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=True, max_length=255)),
                ('title', models.CharField(default=True, max_length=255)),
                ('image', models.URLField(default=True)),
                ('link', models.URLField(default=True)),
                ('price', models.CharField(default=True, max_length=50)),
                ('description', models.TextField(default='-')),
                ('model', models.CharField(default=True, max_length=255)),
                ('ram', models.CharField(default=True, max_length=50)),
                ('generation', models.CharField(default='-', max_length=50)),
                ('display', models.CharField(default='-', max_length=50)),
                ('storage', models.CharField(default='-', max_length=50)),
                ('processor', models.CharField(blank=True, default='-', max_length=250)),
                ('touchscreen', models.CharField(blank=True, default='-', max_length=100)),
                ('graphics', models.CharField(blank=True, default='-', max_length=250)),
                ('maximum_display_resulation', models.CharField(blank=True, default='-', max_length=100)),
                ('color', models.CharField(blank=True, default='-', max_length=100)),
                ('warrenty', models.CharField(blank=True, default='-', max_length=100)),
                ('insurance', models.CharField(blank=True, default='-', max_length=100)),
                ('battery', models.CharField(blank=True, default='-', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='-', max_length=200)),
                ('ports_and_connectivity', models.CharField(blank=True, default='-', max_length=400)),
                ('brand', models.CharField(blank=True, default='-', max_length=100)),
                ('p_speed', models.CharField(blank=True, default='-', max_length=200)),
                ('img1', models.URLField(blank=True, default=True)),
                ('img2', models.URLField(blank=True, default=True)),
                ('img3', models.URLField(blank=True, default=True)),
                ('logo_url', models.URLField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=True, max_length=255)),
                ('title', models.CharField(default=True, max_length=255)),
                ('image', models.URLField(default=True)),
                ('link', models.URLField(default=True)),
                ('price', models.CharField(default=True, max_length=50)),
                ('description', models.TextField(default='-')),
                ('model', models.CharField(default=True, max_length=255)),
                ('ram', models.CharField(default=True, max_length=50)),
                ('generation', models.CharField(default='-', max_length=50)),
                ('display', models.CharField(default='-', max_length=50)),
                ('storage', models.CharField(default='-', max_length=50)),
                ('processor', models.CharField(blank=True, default='-', max_length=250)),
                ('touchscreen', models.CharField(blank=True, default='-', max_length=100)),
                ('graphics', models.CharField(blank=True, default='-', max_length=250)),
                ('maximum_display_resulation', models.CharField(blank=True, default='-', max_length=100)),
                ('color', models.CharField(blank=True, default='-', max_length=100)),
                ('warrenty', models.CharField(blank=True, default='-', max_length=100)),
                ('insurance', models.CharField(blank=True, default='-', max_length=100)),
                ('battery', models.CharField(blank=True, default='-', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='-', max_length=200)),
                ('ports_and_connectivity', models.CharField(blank=True, default='-', max_length=400)),
                ('brand', models.CharField(blank=True, default='-', max_length=100)),
                ('p_speed', models.CharField(blank=True, default='-', max_length=200)),
                ('img1', models.URLField(blank=True, default=True)),
                ('img2', models.URLField(blank=True, default=True)),
                ('img3', models.URLField(blank=True, default=True)),
                ('logo_url', models.URLField(blank=True, default=True)),
            ],
        ),
    ]
