# Generated by Django 2.2 on 2023-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_filtereditti_filteredneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered',
            name='logo',
            field=models.URLField(default='https://www.infotechsnepal.com/wp-content/uploads/2023/02/InfoTechs-Logo.png'),
        ),
        migrations.AddField(
            model_name='filtereditti',
            name='logo',
            field=models.URLField(default='https://itti.com.np/pub/media/logo/stores/1/itti-logo.png'),
        ),
        migrations.AddField(
            model_name='filteredneo',
            name='logo',
            field=models.URLField(default='https://neostore.com.np/assets/images/neologohigh.png'),
        ),
    ]
