# Generated by Django 2.2 on 2023-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20230902_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoneNeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=100)),
                ('display_size', models.CharField(max_length=20)),
                ('battery_power', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('internal_storage', models.CharField(max_length=50)),
                ('primary_camera', models.CharField(max_length=50)),
                ('secondary_camera', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('sim_type', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('images', models.ManyToManyField(related_name='product_images', to='shop.ProductImage')),
            ],
        ),
    ]
