# Generated by Django 2.2 on 2023-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productimage_productphoneneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoneneo',
            name='logo',
            field=models.URLField(default='https://neostore.com.np/assets/images/neologohigh.png'),
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='pprice',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productphoneneo',
            name='images',
            field=models.ManyToManyField(related_name='products', to='shop.ProductImage'),
        ),
    ]
