# Generated by Django 2.2 on 2023-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20230902_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoneneo',
            name='link',
            field=models.URLField(default=True),
        ),
        migrations.RemoveField(
            model_name='productphoneneo',
            name='images',
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='images',
            field=models.URLField(default=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
