# Generated by Django 2.2 on 2023-09-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20230902_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoneneo',
            name='internal_storage',
        ),
        migrations.RemoveField(
            model_name='productphoneneo',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='productphoneneo',
            name='product_type',
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='description',
            field=models.CharField(default=True, max_length=400),
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='insurance',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='model',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productphoneneo',
            name='storage',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
