# Generated by Django 2.2 on 2023-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20230902_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoneDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(default=True, max_length=100, null=True)),
                ('image', models.URLField()),
                ('price_range', models.CharField(default=100, max_length=100, null=True)),
                ('price', models.CharField(default=True, max_length=100, null=True)),
                ('brand', models.CharField(default=True, max_length=100, null=True)),
                ('model', models.CharField(default=True, max_length=100, null=True)),
                ('color', models.CharField(default=True, max_length=100, null=True)),
                ('sim_type', models.CharField(default=True, max_length=100, null=True)),
                ('sound', models.CharField(default=True, max_length=100, null=True)),
                ('date', models.CharField(default=True, max_length=100, null=True)),
                ('dimensions', models.CharField(default=True, max_length=100, null=True)),
                ('weight', models.CharField(default=True, max_length=100, null=True)),
                ('display', models.CharField(default=True, max_length=100, null=True)),
                ('type', models.CharField(default=True, max_length=100, null=True)),
                ('touchscreen', models.CharField(default=True, max_length=100, null=True)),
                ('resolution', models.CharField(default=True, max_length=100, null=True)),
                ('density', models.CharField(default=True, max_length=100, null=True)),
                ('protection', models.CharField(default=True, max_length=100, null=True)),
                ('rear_camera', models.CharField(default=True, max_length=100, null=True)),
                ('rear_camera_extra', models.CharField(default=True, max_length=100, null=True)),
                ('camera_features', models.CharField(default=True, max_length=100, null=True)),
                ('front_camera', models.CharField(default=True, max_length=100, null=True)),
                ('front_camera_extra', models.CharField(default=True, max_length=100, null=True)),
                ('video', models.CharField(default=True, max_length=100, null=True)),
                ('processor', models.CharField(default=True, max_length=100, null=True)),
                ('cpu', models.CharField(default=True, max_length=100, null=True)),
                ('gpu', models.CharField(default=True, max_length=100, null=True)),
                ('ram', models.CharField(default=True, max_length=100, null=True)),
                ('storage', models.CharField(default=True, max_length=100, null=True)),
                ('expandablememory', models.CharField(default=True, max_length=100, null=True)),
                ('memorycardslot', models.CharField(default=True, max_length=100, null=True)),
                ('operatingsystem', models.CharField(default=True, max_length=100, null=True)),
                ('technology', models.CharField(default=True, max_length=100, null=True)),
                ('wlan', models.CharField(default=True, max_length=100, null=True)),
                ('nfc', models.CharField(default=True, max_length=100, null=True)),
                ('usb', models.CharField(default=True, max_length=100, null=True)),
                ('battery', models.CharField(default=True, max_length=100, null=True)),
                ('charger', models.CharField(default=True, max_length=100, null=True)),
                ('sensors', models.CharField(default=True, max_length=100, null=True)),
                ('extra_sensor', models.CharField(default=True, max_length=100)),
                ('warranty', models.CharField(default=True, max_length=100, null=True)),
            ],
        ),
    ]
