# Generated by Django 2.2 on 2023-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_productphonedeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphonedeal',
            name='image',
        ),
        migrations.AddField(
            model_name='productphonedeal',
            name='image_url',
            field=models.URLField(default=True),
        ),
    ]
